---
# tasks file for roles/osp-instance-delete
#  - name: Fetch Instance Info

# tasks file for osp.servers
- name: Delete instances
  os_server:
    auth:
      auth_url: http://192.0.2.21:5000
      username: "admin"
      password: "r3dh4t1!"
      project_id: 4e07f423a12f437388a97a533bb9eef9
      project_name: "admin"
      user_domain_name: "Default"
    region_name: "regionOne"
    interface: "public"
    state: "{{ item.value.state }}"
    validate_certs: False
    name: "{{ item.value.name }}"
  with_dict: "{{ osp_servers }}"

   
