---
# tasks file for osp.servers
- name: Configuration of Servers
  os_server:
    auth:
      auth_url: http://192.0.2.21:5000
      username: "admin"
      password: "r3dh4t1!"
      project_id: 4e07f423a12f437388a97a533bb9eef9
      project_name: "admin"
      user_domain_name: "Default"
    region_name: "regionOne"
    interface: "public"
    state: "{{ item.value.state }}" 
    name: "{{ item.value.name }}"
    image: "{{ item.value.image }}"
    key_name: "{{ item.value.key_name }}"
    flavor: "{{ item.value.flavor }}"
    nics: "{{ item.value.nics }}"
    security_groups: "{{ item.value.security_group }}"
    group: "{{ item.value.meta.group }}"
    userdata: |
      #!/bin/bash
      cat /root/.ssh/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
      cat /root/.ssh/openstack.pem > /home/cloud-user/.ssh/openstack.pem
      cat /root/.ssh/mykey.pem > /home/cloud-user/.ssh/mykey.pem
      chmod 0400 /home/cloud-user/.ssh/openstack.pem
      chmod 0400 /home/cloud-user/.ssh/mykey.pem
      chmod 0400 /home/cloud-user/.ssh/authorized_keys
  with_dict: "{{ osp_servers }}"
